import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav className={`${inter.className} py-3 px-4 bg-black`}>
        <h1 className='text-white'>About navbar</h1>
        <main className='h-screen grid place-content-center text-white'>
          {children}
        </main>
      </nav>
    </>
  );
}
